name: go-cqhttp-ffmpeg-action docker build
on:
  workflow_dispatch:
    inputs:
        name:
          description: 'create go-cqhttp-ffmpeg-action docker image'
          required: true
          default: 'create go-cqhttp-ffmpeg-action docker image'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          path: my-repo

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: Mrs4s/go-cqhttp
          ref: dev
          path: go-cqhttp

      - name: Get current date
        id: date
        run: |
          echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Replace Dockerfile
        run: |
          rm -rf $GITHUB_WORKSPACE/go-cqhttp/Dockerfile
          cp $GITHUB_WORKSPACE/my-repo/go-cqhttp-ffmpeg-action/dockerfile $GITHUB_WORKSPACE/go-cqhttp/dockerfile
          cd $GITHUB_WORKSPACE/go-cqhttp/
        
      - name: go-cqhttp version
        id: version
        run: |
          echo "version=$(curl -sSL https://api.github.com/repos/Mrs4s/go-cqhttp/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            raventu/go-cqhttp-ffmpeg-action:latest
            raventu/go-cqhttp-ffmpeg-action:${{ env.version }}-${{ env.today }}
            raventu/go-cqhttp-ffmpeg:${{ env.version }}-${{ env.today }}-action
          context: ./go-cqhttp/
          platforms: linux/amd64
